### PR TITLE
is_zip_safe: return False to avoid creating incorrectly zip-safe pkgs

### PR DESCRIPTION
**Pull request by immerrr**
`False` should be a much safer default value for `is_zip_safe`, because there's no harm in unpacking an egg file that doesn't need to be unpacked, whereas if you guess incorrectly the other way around you risk running into "file not found" issues.

This already happened for me with a package that contained jinja templates and specified `zip_safe=False` in setup.py. pip wheel ignored the flag, as it extracts the contents anyway, and humpty created a broken egg because of that.

### CODE REVIEW

**Comment by immerrr** [comment]
I have also opened [an issue against distlib](https://bitbucket.org/pypa/distlib/issues/95/make-wheelis_mountable-false-by-default), under the same assumption that `False` is a safer default value, so hopefully this is a temporary measure.

**Comment by immerrr** [comment]
As discussed in the distlib issue, it's probably too late to change the default in such a "deep" library, so the only hope we, the users of humpty, have is that the default is changed here, because it's quite rare for someone to use "mount" a wheel, yet eggs are "mounted" by easy install whenever possible.

**Comment by dairiki** [comment]
Thank you!
This has been implemented in 6f5d5e8 and released in humpty 0.2.

**Comment by immerrr** [comment]
Sweet, thank you very much!

**Pull request closed without merging**
